apiVersion: v2
name: geoserver-api
description: A Helm chart for geoserver-api service
type: application
version: 1.4.1
appVersion: 1.4.1
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
