apiVersion: v2
name: geoserver-api
description: A Helm chart for geoserver-api service
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
- name: common
  repository: oci://acrarolibotnonprod.azurecr.io/helm
  version: 1.0.1
